"""
contracts/plan.py - Financial Plan Data Contracts
===================================================

Defines the Pydantic models that represent a structured financial plan.
These models are the **data contract** between the multi-agent workflow
(internal) and the HTTP response layer (external).

The ``Plan`` model is always present in the ``/api/agents/process``
response -- even when the LLM is unavailable, a deterministic plan is
generated by ``tools.plan_builder.build_plan()``.

Models
------
- ``KeyMetrics`` -- the five headline financial metrics (cash flow,
  savings rate, debt-to-income, emergency fund runway, total debt).
- ``ActionItem`` -- a single recommended action with priority, steps,
  expected impact, and due date.
- ``ActionBuckets`` -- actions grouped by urgency (7 days, 30 days,
  12 months).
- ``Plan`` -- the top-level plan with executive summary, metrics,
  actions, assumptions, and data warnings.
"""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class KeyMetrics(BaseModel):
    """Headline financial metrics extracted from the user's profile and analysis."""
    monthly_net_cash_flow: Optional[float] = None
    savings_rate: Optional[float] = None
    debt_to_income: Optional[float] = None
    emergency_fund_months: Optional[float] = None
    total_debt: Optional[float] = None


class ActionItem(BaseModel):
    title: str
    why: str
    steps: List[str] = Field(default_factory=list)
    priority: Literal["low", "medium", "high"] = "medium"
    expected_impact: str
    kind: Literal["cashflow", "budget", "debt", "invest", "goal", "education", "generic"] = "generic"
    due_days: Optional[int] = None
    id: Optional[str] = None


class ActionBuckets(BaseModel):
    next_7_days: List[ActionItem] = Field(default_factory=list)
    next_30_days: List[ActionItem] = Field(default_factory=list)
    next_12_months: List[ActionItem] = Field(default_factory=list)


class Plan(BaseModel):
    executive_summary: str
    key_metrics: KeyMetrics = Field(default_factory=KeyMetrics)
    actions: ActionBuckets = Field(default_factory=ActionBuckets)
    assumptions: List[str] = Field(default_factory=list)
    data_warnings: List[str] = Field(default_factory=list)
