/**
 * @fileoverview AI-Generated Task Management API
 *
 * Handles the lifecycle of actionable tasks produced by the AI financial
 * planning system. Tasks are the bridge between AI recommendations and
 * real financial actions -- the AI generates a plan, the plan is broken
 * into tasks, and the user can review, complete, or dismiss each one.
 *
 * Key concepts:
 * - **Task Lifecycle**: Tasks flow through statuses: `open` -> `completed`
 *   or `dismissed`. Completion may carry side-effects that the user can
 *   optionally "apply" to their financial data.
 * - **Task Effects (TaskEffect)**: When a task is completed, it can propose
 *   financial side-effects such as creating a transaction, advancing a goal,
 *   making a debt payment, or updating the user's profile. Effects are
 *   defined as a discriminated union on `type`.
 * - **Bucket**: Tasks are categorised by urgency horizon: 7-day, 30-day,
 *   or 365-day.
 * - **Apply Workflow**: After a task is completed, the user can call
 *   `applyTaskEffects` to actually execute the proposed side-effects on
 *   the server. This is an idempotent operation.
 *
 * All functions delegate to the shared `apiClient` for consistent
 * authentication, error handling, and organisation context.
 */

import { apiClient } from "./core";
import type { MutationSource, TransactionType } from "./transactions";

/** Possible statuses a task can be in. */
export type TaskStatus = "open" | "completed" | "dismissed";
/**
 * Discriminated union of financial side-effects a completed task can propose.
 * Each variant targets a different domain entity (transaction, goal, debt, profile).
 */
export type TaskEffect =
  | {
      type: "transaction";
      transaction: {
        amount: number;
        category: string;
        description: string;
        date?: string;
        tx_type: TransactionType;
      };
    }
  | {
      type: "goal_progress";
      goal_id: string;
      amount: number;
      /** "increment" adds to current, "set" replaces the value. */
      mode?: "increment" | "set";
    }
  | {
      type: "debt_payment";
      debt_id: string;
      amount: number;
    }
  | {
      type: "profile_update";
      updates: {
        annual_income?: number;
        monthly_expenses?: number;
        savings?: number;
      };
    };

/** A single actionable task generated by the AI planning system. */
export interface Task {
  _id: string;
  /** Traceability: which AI output / chat message produced this task. */
  source?: { agentOutputId?: string; chatMessageId?: string; requestId?: string };
  /** Urgency horizon: 7-day (immediate), 30-day (short-term), or 365-day (long-term). */
  bucket: 7 | 30 | 365;
  title: string;
  why: string;
  steps: string[];
  priority: "low" | "medium" | "high";
  expected_impact: string;
  kind: string;
  dueDate?: string;
  status: TaskStatus;
  completedAt?: string;
  /** Evidence captured when the user marks the task as completed. */
  completionEvidence?: {
    note?: string;
    completedAt?: string;
    effects?: TaskEffect[];
  };
  /** Timestamp and record of when proposed effects were applied. */
  appliedAt?: string;
  appliedSummary?: {
    transactions: string[];
    goals: string[];
    debts: string[];
    profileUpdated: boolean;
  };
  /** Status of the effect-application step: pending -> succeeded | failed. */
  applyStatus?: "pending" | "succeeded" | "failed";
  applyErrorCode?: string;
  applyIdempotencyKey?: string;
  /** Link to a UI action card that can deep-link to this task. */
  actionLinkId?: string;
  /** References to outcomes generated when effects were applied. */
  outcomeRefs?: string[];
}

/**
 * Ask the server to decompose an AI plan into individual tasks.
 * The optional `source` links each created task back to the originating
 * agent output or chat message for traceability.
 */
export async function createTasksFromPlan(payload: {
  source?: { agentOutputId?: string; chatMessageId?: string; requestId?: string };
  plan: any;
}): Promise<{ created: number; tasks: Task[] }> {
  return apiClient("/tasks/from-plan", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * Fetch tasks filtered by status, with a clamped limit (1-100, default 50).
 * Defaults to "open" tasks when no status is specified.
 */
export async function getTasks(params: { status?: TaskStatus; limit?: number } = {}): Promise<{ tasks: Task[] }> {
  const status = params.status || "open";
  // Clamp limit to a sane range to prevent accidental large fetches.
  const limit = Math.max(1, Math.min(100, Number(params.limit) || 50));
  const qs = new URLSearchParams({ status, limit: String(limit) });
  return apiClient(`/tasks?${qs.toString()}`);
}

/**
 * Update a task's status (and optionally attach completion evidence / effects).
 * This is a PATCH -- only the provided fields are overwritten.
 */
export async function updateTaskStatus(
  taskId: string,
  status: TaskStatus,
  options: {
    completed_at?: string;
    note?: string;
    effects?: TaskEffect[];
    completion_evidence?: { note?: string; completed_at?: string };
    apply_status?: "pending" | "succeeded" | "failed";
    apply_error_code?: string;
  } = {}
): Promise<{ task: Task }> {
  return apiClient(`/tasks/${taskId}`, {
    method: "PATCH",
    body: JSON.stringify({ status, ...options }),
  });
}

/**
 * Execute the proposed side-effects of a completed task on the server.
 * This is an idempotent operation -- replaying the same request returns
 * the original result without duplicating effects.
 */
export async function applyTaskEffects(
  taskId: string,
  payload: { idempotency_key?: string; completed_at?: string; note?: string; effects?: TaskEffect[] } = {}
): Promise<{
  task: Task;
  applied_effects: {
    transactions: string[];
    goals: string[];
    debts: string[];
    profile_updated: boolean;
  };
  links: {
    action_link_id: string;
    task_id: string;
    transaction_ids: string[];
    goal_ids: string[];
    debt_ids: string[];
  };
  provenance: MutationSource;
  idempotent_replay?: boolean;
  request_id?: string;
}> {
  return apiClient(`/tasks/${taskId}/apply`, {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/** Fetch a single task by ID, including its source agent output if available. */
export async function getTaskById(taskId: string): Promise<{
  task: Task;
  source?: {
    agent_output: null | {
      id: string;
      request_id?: string;
      user_input_snippet: string;
      title?: string;
    };
  };
  request_id?: string;
}> {
  return apiClient(`/tasks/${taskId}`);
}
